package cdioil.backoffice.webapp;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.VerticalLayout;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainLayoutDesign extends CssLayout {
    protected HorizontalLayout leftAndRightLayout;
    protected Panel leftPanel;
    protected Image userAvatar;
    protected Label usernameLabel;
    protected VerticalLayout btnPanel;
    protected Panel rightPanel;

    public MainLayoutDesign() {
        Design.read(this);
    }
}
