package cdioil.backoffice.webapp.admin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AdminPanelDesign extends CssLayout {
    protected Panel panelManager;
    protected Image imgManager;
    protected Label lblName;
    protected Button btnHome;
    protected Button btnAddManager;
    protected Button btn3;
    protected Button btn4;
    protected Button btn5;
    protected Button btnConta;
    protected Button btnLogout;
    protected Panel rightPanel;
    protected Label lblUserName;
    protected Panel dashboardPanel;
    protected Image logoHomeImg;

    public AdminPanelDesign() {
        Design.read(this);
    }
}
